{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "airflow-k8s-operator.fullname" . }}-podmonitor
  labels:
    {{- include "airflow-k8s-operator.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "airflow-k8s-operator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval | quote }}
      timeout: {{ .Values.podMonitor.timeout | quote }}
      path: {{ .Values.podMonitor.path | default "/metrics" | quote }}
{{- end }}
