---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "airflow-k8s-operator.fullname" . }}-cluster-role
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
  - apiGroups: [airflow.drfaust92]
    resources: [variables, connections]
    verbs: [list, watch, get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "airflow-k8s-operator.fullname" . }}-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "airflow-k8s-operator.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow-k8s-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
