# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- (string) the repository of the image
  repository: ghcr.io/drfaust92/airflow-k8s-operator
  # -- (string) the image pull policy
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # -- (string) the image tag (overrides chart appVersion)
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# -- (list) image pull secrets for private registries
imagePullSecrets: []
# This is to override the chart name.
# -- (string) short chart name override
nameOverride: ""
# -- (string) full chart name override
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # -- (bool) whether to automount the service account token
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- (map) annotations to add to the service account
  # Annotations to add to the service account.
  annotations: {}
  # -- (string) service account name (optional)
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
# -- (map) annotations to add to the pod
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
# -- (map) labels to add to the pod
podLabels: {}

# -- (map) pod-level security context
podSecurityContext:
  {}
  # fsGroup: 2000

# -- (map) container security context
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # -- (map) resource requests and limits
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- (map) liveness probe configuration
livenessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes:
  # -- (list) additional volumes to add to the pod
  []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  # -- (list) additional volumeMounts for the container
  []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

## Container environment variables
## - Provide a list of environment variables to set in the container.
## - Each item should be a mapping with `name` and either `value` or a valueFrom reference.
## - Example items are shown below.
# -- (list) environment variables for the container (name/value entries)
env:
  []
  # - name: AIRFLOW_HOST
  #   value: "http://airflow-webserver:8080"
  # - name: AIRFLOW_USERNAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: airflow-credentials
  #       key: username
  # - name: AIRFLOW_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: airflow-credentials
  #       key: password

## Environment variables from a ConfigMap or Secret
## - Use `envFrom` to populate environment variables from a `configMapRef` or `secretRef`.
## - Each entry should be a map with either `configMapRef` or `secretRef` pointing to an existing resource.
# -- (list) envFrom sources (configMapRef or secretRef)
envFrom:
  []
  # - configMapRef:
  #     name: my-config-map
  # - secretRef:
  #     name: my-secret

## -- (map) node selector constraints
nodeSelector: {}

## -- (list) Kubernetes tolerations for the pod
tolerations: []

## -- (map) affinity rules for pod scheduling
affinity: {}

port: 8080

operator:
  # -- (string) log level for the operator
  logLevel: "INFO"

  # -- (string) log format for the operator
  logFormat: "json"

  # -- (string) liveness probe address for the operator
  livenessProbeAddress: "http://0.0.0.0:{{ .Values.port }}/healthz"
