apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pools.airflow.drfaust92
spec:
  group: airflow.drfaust92
  scope: Namespaced
  names:
    kind: Pool
    plural: pools
    singular: pool
    shortNames:
      - pls
      - pl
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - slots
              properties:
                slots:
                  type: integer
                  description: The maximum number of slots that can be assigned to tasks. One job may occupy one or more slots.
                includeDeferred:
                  type: boolean
                  description: Whether to include deferred tasks in the pool.  
                description:
                  type: string
                  description: The pool description.
