name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5 # uses .python-version file by default
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      
      - name: Install dependencies
        run: uv sync
      
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Add Airflow Helm repository
        run: helm repo add apache-airflow https://airflow.apache.org && helm repo update
      
      - name: Install Airflow
        run: |
          helm install airflow apache-airflow/airflow \
            --set executor=KubernetesExecutor \
            --set workers.replicas=0 \
            --set flower.enabled=false \
            --set redis.enabled=false \
            --set postgresql.enabled=true \
            --set webserver.replicas=1 \
            --set scheduler.replicas=1 \
            --set triggerer.enabled=false \
            --set statsd.enabled=false \
            --set pgbouncer.enabled=false \
            --timeout 10m \
            --wait

    #   - name: install test dependencies
    #     run: uv sync --group test

    #   - name: Run operator test
    #     run: uv run pytest tests/operator_test.py
